on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

permissions: 
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v3
      - uses: moonrepo/setup-rust@v1
      - run: ./sync.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: sync


